variant = "loose"

[[issues]]
file = "src/Install.php"
code = "literal-named-argument"
message = "Literal argument `'/'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Install.php"
code = "literal-named-argument"
message = "Literal argument `0` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Install.php"
code = "literal-named-argument"
message = "Literal argument `0o777` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Install.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/Install.php"
code = "str-contains"
message = "Consider replacing `strpos` with `!str_contains` for improved readability and intent clarity."
count = 2

[[issues]]
file = "src/JwtToken.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/JwtToken.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/JwtToken.php"
code = "literal-named-argument"
message = "Literal argument `'.'` should be passed as a named argument for clarity."
count = 1

[[issues]]
file = "src/JwtToken.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 3

[[issues]]
file = "src/JwtToken.php"
code = "no-insecure-comparison"
message = "Insecure comparison of sensitive data."
count = 6

[[issues]]
file = "src/JwtToken.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 8

[[issues]]
file = "src/JwtToken.php"
code = "no-literal-password"
message = "Literal passwords or sensitive data should not be stored in code."
count = 2

[[issues]]
file = "src/JwtToken.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "src/RedisHandler.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/RedisHandler.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1

[[issues]]
file = "src/config/plugin/tinywan/jwt/app.php"
code = "prefer-arrow-function"
message = "This closure can be simplified to a more concise arrow function."
count = 1

[[issues]]
file = "src/config/plugin/tinywan/jwt/app.php"
code = "strict-types"
message = "Missing `declare(strict_types=1);` statement at the beginning of the file."
count = 1

[[issues]]
file = "tests/config/plugin/tinywan/jwt/app.php"
code = "prefer-arrow-function"
message = "This closure can be simplified to a more concise arrow function."
count = 1
