<?php
/**
 * @desc JwtTokenTest.php 描述信息
 * @author Tinywan(ShaoBo Wan)
 * @date 2022/2/24 10:04
 */


namespace Tinywan\Tests;


use Tinywan\Jwt\JwtToken;
use Tinywan\Jwt\RedisHandler;
use Tinywan\Jwt\Exception\RedisConnectionException;

class JwtTokenTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGenerateToken()
    {
        $user = [
            'id'  => 2022,
            'name'  => 'Tinywan',
            'email' => 'Tinywan@163.com'
        ];
        $token = JwtToken::generateToken($user);
        self::assertIsArray($token);
    }

    public function testRedisAvailability()
    {
        $isAvailable = RedisHandler::isAvailable();
        $this->assertIsBool($isAvailable);
    }

    public function testGenerateTokenWithInvalidTtl()
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('TTL必须大于0');
        
        RedisHandler::generateToken('test:', 'WEB', '123', -1, 'test-token');
    }

    public function testGenerateTokenWithEmptyToken()
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Token不能为空');
        
        RedisHandler::generateToken('test:', 'WEB', '123', 3600, '');
    }

    public function testVerifyTokenWithEmptyToken()
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Token不能为空');
        
        RedisHandler::verifyToken('test:', 'WEB', '123', '');
    }
}