name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality:
    name: Quality (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.2"
          - "8.3"
          - "8.4"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug
      - run: composer install --no-interaction --prefer-dist
      - run: composer format:check
      - run: composer lint
      - run: composer analyse
      - run: composer test -- --coverage-clover=coverage.xml --coverage-filter=src

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
